export const STATUS_LABELS: Record<string, string> = {
  NEW: "جديد",
  PENDING: "معلق",
  ACCEPTED: "مقبول",
  PREPARING: "جاري التحضير",
  READY: "جاهز",
  COMPLETED: "مكتمل",
  CANCELLED: "ملغي",
  PAID: "مدفوع",
  FAILED: "فشل",
  PARTIALLY_REFUNDED: "مسترجع جزئيًا",
  REFUNDED: "مسترجع",
  ACTIVE: "نشط",
  INACTIVE: "غير نشط",
  SUSPENDED: "موقوف",
  TRIAL: "تجريبي",
  TRIALING: "فترة تجريبية",
  PAST_DUE: "متأخر",
  CANCELED: "ملغي",
  OPEN: "مفتوحة",
  CLOSED: "مغلقة",
  DRAFT: "مسودة",
  ORDERED: "تم الطلب",
  RECEIVED: "مستلمة",
  ACCEPTED_REQUEST: "مستلم",
  READ: "مقروء",
  UNREAD: "غير مقروء",
};

export const STATUS_STYLES: Record<string, string> = {
  ACTIVE: "border-emerald-200 bg-emerald-50 text-emerald-700",
  PAID: "border-emerald-200 bg-emerald-50 text-emerald-700",
  COMPLETED: "border-emerald-200 bg-emerald-50 text-emerald-700",
  READY: "border-emerald-200 bg-emerald-50 text-emerald-700",
  CLOSED: "border-slate-200 bg-slate-50 text-slate-700",
  NEW: "border-sky-200 bg-sky-50 text-sky-700",
  ACCEPTED: "border-blue-200 bg-blue-50 text-blue-700",
  OPEN: "border-blue-200 bg-blue-50 text-blue-700",
  PENDING: "border-amber-200 bg-amber-50 text-amber-700",
  PREPARING: "border-amber-200 bg-amber-50 text-amber-700",
  PARTIALLY_REFUNDED: "border-amber-200 bg-amber-50 text-amber-700",
  TRIALING: "border-amber-200 bg-amber-50 text-amber-700",
  FAILED: "border-red-200 bg-red-50 text-red-700",
  CANCELLED: "border-red-200 bg-red-50 text-red-700",
  CANCELED: "border-red-200 bg-red-50 text-red-700",
  SUSPENDED: "border-red-200 bg-red-50 text-red-700",
  REFUNDED: "border-violet-200 bg-violet-50 text-violet-700",
};
