"use client";
import { ArrowUpRight, ClipboardList, DoorOpen, ReceiptText, TableProperties, Users } from "lucide-react";
import { AdminShell } from "@/components/admin/admin-shell";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Price } from "@/components/shared/price";
import { mockDashboardStats, mockRecentOrders } from "@/mocks/dashboard.mock";
import { useAdminLocale } from "@/providers/admin-locale-provider";

const statusStyle: Record<string, string> = { NEW: "bg-sky-500/15 text-sky-300", PREPARING: "bg-amber-500/15 text-amber-300", READY: "bg-emerald-500/15 text-emerald-300", COMPLETED: "bg-muted text-muted-foreground" };

export default function AdminDashboardPage() {
  const { locale } = useAdminLocale();
  const text = locale === "en" ? { overview: "Operations overview", title: "Dashboard", description: "Here’s what’s happening at Golden Drip today.", live: "Open live orders", total: "Total orders", revenue: "Revenue", tables: "Active tables", pending: "Pending orders", recent: "Recent orders", latest: "Latest orders from the café", glance: "Today at a glance" } : { overview: "نظرة عامة على التشغيل", title: "لوحة التحكم", description: "ملخص ما يحدث في جولدن دريب اليوم.", live: "فتح الطلبات الحالية", total: "إجمالي الطلبات", revenue: "الإيرادات", tables: "الطاولات النشطة", pending: "طلبات معلقة", recent: "أحدث الطلبات", latest: "آخر طلبات الكافيه", glance: "ملخص اليوم" };
  const stats = [
    { label: text.total, value: mockDashboardStats.totalOrders, icon: ClipboardList, detail: "+12% this week" },
    { label: text.revenue, value: <Price value={mockDashboardStats.totalRevenue} locale={locale} />, icon: ReceiptText, detail: "+8% this week" },
    { label: text.tables, value: mockDashboardStats.activeTables, icon: TableProperties, detail: "of 10 tables" },
    { label: text.pending, value: mockDashboardStats.pendingOrders, icon: Users, detail: "Needs attention" },
  ];
  return <AdminShell><section className="animate-content-enter mx-auto w-full max-w-7xl px-4 py-8 sm:px-6"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-accent">{text.overview}</p><h1 className="mt-2 text-3xl font-bold">{text.title}</h1><p className="mt-1 text-muted-foreground">{text.description}</p></div><Button className="gap-2"><DoorOpen className="h-4 w-4" />{text.live}</Button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map((stat) => { const Icon = stat.icon; return <Card key={stat.label} className="transition-transform duration-300 hover:-translate-y-1"><CardContent className="p-5"><div className="mb-5 flex items-center justify-between"><span className="text-sm text-muted-foreground">{stat.label}</span><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/15 text-primary"><Icon className="h-5 w-5" /></span></div><div className="text-2xl font-bold">{stat.value}</div><p className="mt-2 flex items-center gap-1 text-xs text-muted-foreground"><ArrowUpRight className="h-3.5 w-3.5 text-emerald-400" />{stat.detail}</p></CardContent></Card>; })}</div><div className="mt-8 grid gap-6 lg:grid-cols-[1.4fr_0.6fr]"><Card><CardContent className="p-0"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-semibold">{text.recent}</h2><p className="text-sm text-muted-foreground">{text.latest}</p></div><Button variant="ghost" size="sm">View all</Button></div><div className="divide-y">{mockRecentOrders.map((order) => <div key={order.id} className="flex items-center justify-between gap-4 p-5"><div><p className="font-medium">{order.orderNumber} <span className="font-normal text-muted-foreground">· Table {order.tableNumber}</span></p><p className="mt-1 text-sm text-muted-foreground"><Price value={order.total} locale={locale} /></p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${statusStyle[order.status]}`}>{order.status}</span></div>)}</div></CardContent></Card><Card><CardContent className="p-5"><h2 className="font-semibold">{text.glance}</h2><div className="mt-6 space-y-5"><Metric label="Order completion" value="74%" /><Metric label="Table occupancy" value="80%" /><Metric label="Customer satisfaction" value="4.8 / 5" /></div></CardContent></Card></div></section></AdminShell>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div><div className="flex justify-between text-sm"><span className="text-muted-foreground">{label}</span><span className="font-semibold">{value}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: value.includes("74") ? "74%" : value.includes("80") ? "80%" : "96%" }} /></div></div>; }
